"use client";
import {FormEvent,useEffect,useState} from "react";
import {Boxes,FolderTree,ImagePlus,LogOut,PackagePlus,ShoppingBag} from "lucide-react";
import {db,uploadProductImage} from "@/lib/supabase-rest";
type Cat={id:string;name:string;slug:string};type Sub={id:string;category_id:string;name:string;slug:string};type Product={id:string;name:string;category_id:string|null;subcategory_id:string|null;description?:string;price:number|null;stock_quantity:number;status:string;image_urls:string[];sku:string|null;featured:boolean;best_seller:boolean;new_arrival:boolean};type Order={id:string;order_number:string;customer_email:string;total:number;currency:string;status:string;payment_status:string};
const slug=(x:string)=>x.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
export default function Admin(){const[token,setToken]=useState("");const[ready,setReady]=useState(false);const[msg,setMsg]=useState("");const[cats,setCats]=useState<Cat[]>([]);const[subs,setSubs]=useState<Sub[]>([]);const[products,setProducts]=useState<Product[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[edit,setEdit]=useState<Product|null>(null);const[uploading,setUploading]=useState(false);
async function load(t:string){try{if(!(await db("admins?select=user_id&limit=1",t)).length)throw Error("This account is not authorised for KAOMA administration.");const[c,s,p,o]=await Promise.all([db("categories?select=id,name,slug&order=sort_order",t),db("subcategories?select=id,category_id,name,slug&order=sort_order",t),db("products?select=*&order=created_at.desc",t),db("orders?select=id,order_number,customer_email,total,currency,status,payment_status&order=created_at.desc",t)]);setCats(c);setSubs(s);setProducts(p);setOrders(o);setReady(true)}catch(e){setMsg(e instanceof Error?e.message:"Unable to load administration")}}
useEffect(()=>{const t=sessionStorage.getItem("kaoma_admin_token")||"";if(!t){location.replace("/admin-login");return}setToken(t);load(t)},[]);
async function addCat(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get("name"));await db("categories",token,{method:"POST",body:JSON.stringify({name,slug:slug(name)})});e.currentTarget.reset();load(token)}
async function addSub(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get("name"));await db("subcategories",token,{method:"POST",body:JSON.stringify({name,slug:slug(name),category_id:String(f.get("category"))})});e.currentTarget.reset();load(token)}
async function saveProduct(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),file=f.get("image") as File;setUploading(true);try{let images=edit?.image_urls||[];if(file?.size)images=[...images,await uploadProductImage(file,token)];const name=String(f.get("name"));const body={name,slug:slug(name),sku:String(f.get("sku"))||null,category_id:String(f.get("category"))||null,subcategory_id:String(f.get("subcategory"))||null,description:String(f.get("description")),price:Number(f.get("price"))||null,compare_at_price:Number(f.get("compare"))||null,stock_quantity:Number(f.get("stock"))||0,sizes:String(f.get("sizes")).split(",").map(x=>x.trim()).filter(Boolean),colours:String(f.get("colours")).split(",").map(x=>x.trim()).filter(Boolean),status:String(f.get("status")),featured:f.get("featured")==="on",best_seller:f.get("best_seller")==="on",new_arrival:f.get("new_arrival")==="on",image_urls:images};await db(edit?`products?id=eq.${edit.id}`:"products",token,{method:edit?"PATCH":"POST",body:JSON.stringify(body)});setEdit(null);e.currentTarget.reset();load(token)}finally{setUploading(false)}}
async function remove(table:string,id:string){if(!confirm("Permanently delete this item?"))return;await db(`${table}?id=eq.${id}`,token,{method:"DELETE"});load(token)}async function orderStatus(id:string,status:string){await db(`orders?id=eq.${id}`,token,{method:"PATCH",body:JSON.stringify({status})});load(token)}function logout(){sessionStorage.removeItem("kaoma_admin_token");location.replace("/admin-login")}
if(!ready)return <main className="adminLoading"><h1>KAOMA Administration</h1><p>{msg||"Opening secure dashboard…"}</p>{msg&&<a className="primary" href="/admin-login">Return to login</a>}</main>;
return <main className="adminPanel"><header className="adminHeader"><div><b>KAOMA</b><span>Advanced administration</span></div><button onClick={logout}><LogOut/>Sign out</button></header><section className="adminIntro"><p>PRIVATE STORE CONTROL</p><h1>Manage everything</h1><span>Categories, subcategories, products, pictures, prices, inventory, publishing and customer orders—on desktop and mobile.</span></section><section className="adminStats"><article><FolderTree/><b>{cats.length}</b><span>Categories</span></article><article><Boxes/><b>{products.length}</b><span>Products</span></article><article><ShoppingBag/><b>{orders.length}</b><span>Orders</span></article></section><section className="adminGrid">
<article className="adminCard"><h2>Categories & subcategories</h2><form onSubmit={addCat}><input name="name" placeholder="Category name" required/><button className="primary">Add category</button></form><form onSubmit={addSub} className="subForm"><select name="category" required><option value="">Parent category</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input name="name" placeholder="Subcategory name" required/><button className="primary">Add subcategory</button></form><div className="adminList">{cats.map(c=><div key={c.id}><span><b>{c.name}</b><small>{subs.filter(s=>s.category_id===c.id).map(s=>s.name).join(" · ")||"No subcategories"}</small></span><button onClick={()=>remove("categories",c.id)}>Delete</button></div>)}</div></article>
<article className="adminCard productEditor"><h2>{edit?"Edit product":"Add product"}</h2><form onSubmit={saveProduct}><input name="name" defaultValue={edit?.name} placeholder="Product name" required/><input name="sku" defaultValue={edit?.sku||""} placeholder="SKU"/><select name="category" defaultValue={edit?.category_id||""}><option value="">Category</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select name="subcategory" defaultValue={edit?.subcategory_id||""}><option value="">Subcategory</option>{subs.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><textarea name="description" defaultValue={edit?.description||""} placeholder="Description"/><div className="adminTwo"><input name="price" type="number" step=".01" defaultValue={edit?.price||""} placeholder="Price"/><input name="compare" type="number" step=".01" placeholder="Compare price"/></div><div className="adminTwo"><input name="stock" type="number" min="0" defaultValue={edit?.stock_quantity||0} placeholder="Stock"/><select name="status" defaultValue={edit?.status||"draft"}><option value="draft">Draft</option><option value="active">Published</option><option value="sold_out">Sold out</option></select></div><input name="sizes" placeholder="Sizes: S, M, L"/><input name="colours" placeholder="Colours: Wine, Rose"/><label className="imageInput"><ImagePlus/>Product picture<input name="image" type="file" accept="image/jpeg,image/png,image/webp"/></label><div className="adminChecks"><label><input name="featured" type="checkbox" defaultChecked={edit?.featured}/>Featured</label><label><input name="best_seller" type="checkbox" defaultChecked={edit?.best_seller}/>Best seller</label><label><input name="new_arrival" type="checkbox" defaultChecked={edit?.new_arrival}/>New arrival</label></div><button className="primary" disabled={uploading}><PackagePlus/>{uploading?"Uploading…":edit?"Save changes":"Add product"}</button>{edit&&<button type="button" className="textButton" onClick={()=>setEdit(null)}>Cancel editing</button>}</form></article>
<article className="adminCard adminWide"><h2>Products</h2><div className="adminList">{products.length?products.map(p=><div key={p.id}><span><b>{p.name}</b><small>{p.status} · Stock {p.stock_quantity} · {p.price?`₹${p.price}`:"No price"} · {p.image_urls?.length||0} pictures</small></span><span className="rowActions"><button onClick={()=>setEdit(p)}>Edit</button><button onClick={()=>remove("products",p.id)}>Delete</button></span></div>):<p>No products added yet.</p>}</div></article>
<article className="adminCard adminWide"><h2>Orders</h2><div className="adminList">{orders.length?orders.map(o=><div key={o.id}><span><b>{o.order_number}</b><small>{o.customer_email} · {o.currency} {o.total} · Payment {o.payment_status}</small></span><select value={o.status} onChange={e=>orderStatus(o.id,e.target.value)}><option>pending</option><option>confirmed</option><option>packed</option><option>shipped</option><option>delivered</option><option>cancelled</option></select></div>):<p>No customer orders yet.</p>}</div></article>
</section></main>}
