"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { db } from "@/lib/supabase-rest";

type Product={id:string;name:string;stock_quantity:number};
type Coupon={id:string;code:string;discount_type:string;discount_value:number;minimum_order:number;active:boolean;usage_count:number};
type ReturnRequest={id:string;order_id:string;reason:string;details?:string;status:string;admin_note?:string;created_at:string};

export function CommerceGrowthAdmin({token,products}:{token:string;products:Product[]}) {
  const [coupons,setCoupons]=useState<Coupon[]>([]),[returns,setReturns]=useState<ReturnRequest[]>([]),[message,setMessage]=useState("");
  const lowStock=useMemo(()=>products.filter(p=>p.stock_quantity<=5),[products]);
  async function load(){try{const [c,r]=await Promise.all([db("coupons?select=*&order=created_at.desc",token),db("return_requests?select=*&order=created_at.desc",token)]);setCoupons(c);setReturns(r);}catch{setMessage("Run the KAOMA growth-suite SQL once to activate these tools.");}}
  useEffect(()=>{if(token)void load()},[token]);
  async function addCoupon(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);try{await db("coupons?on_conflict=code",token,{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({code:String(f.get("code")).trim().toUpperCase(),discount_type:String(f.get("type")),discount_value:Number(f.get("value")),minimum_order:Number(f.get("minimum")||0),maximum_discount:Number(f.get("maximum")||0)||null,usage_limit:Number(f.get("limit")||0)||null,active:true})});form.reset();setMessage("Coupon saved successfully.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Unable to create coupon.")}}
  async function toggleCoupon(c:Coupon){await db(`coupons?id=eq.${c.id}`,token,{method:"PATCH",body:JSON.stringify({active:!c.active})});await load()}
  async function updateReturn(id:string,status:string){await db(`return_requests?id=eq.${id}`,token,{method:"PATCH",body:JSON.stringify({status,updated_at:new Date().toISOString()})});await load()}
  return <><article className="adminCard adminWide growthAdmin"><h2>Promotional coupons</h2>{message&&<p className="adminNotice">{message}</p>}<form onSubmit={addCoupon} className="settingsForm"><label>Coupon code<input name="code" placeholder="WELCOME10" required/></label><label>Discount type<select name="type"><option value="percentage">Percentage</option><option value="fixed">Fixed INR amount</option></select></label><label>Discount value<input name="value" type="number" min="1" step=".01" required/></label><label>Minimum order<input name="minimum" type="number" min="0" defaultValue="0"/></label><label>Maximum discount (optional)<input name="maximum" type="number" min="0"/></label><label>Usage limit (optional)<input name="limit" type="number" min="1"/></label><button className="primary">Create coupon</button></form><div className="adminList">{coupons.map(c=><div key={c.id}><span><b>{c.code}</b><small>{c.discount_value}{c.discount_type==="percentage"?"%":" INR"} off · Used {c.usage_count||0}</small></span><button onClick={()=>void toggleCoupon(c)}>{c.active?"Disable":"Enable"}</button></div>)}</div></article><article className="adminCard"><h2>Low-stock alerts</h2><div className="adminList">{lowStock.length?lowStock.map(p=><div key={p.id}><span><b>{p.name}</b><small>{p.stock_quantity===0?"Out of stock":`Only ${p.stock_quantity} remaining`}</small></span></div>):<p>All products have healthy stock.</p>}</div></article><article className="adminCard"><h2>Return and refund requests</h2><div className="adminList">{returns.length?returns.map(r=><div key={r.id}><span><b>{r.reason}</b><small>Order {r.order_id} · {r.details||"No additional details"}</small></span><select value={r.status} onChange={e=>void updateReturn(r.id,e.target.value)}><option>requested</option><option>reviewing</option><option>approved</option><option>rejected</option><option>refunded</option></select></div>):<p>No return requests.</p>}</div></article></>;
}
