"use client";
import { FormEvent, useEffect, useState } from "react";
import { db } from "@/lib/supabase-rest";
type Address={id:string;label:string;full_name:string;phone:string;country:string;address_line1:string;city:string;region:string;postal_code:string;is_default:boolean};
type Order={id:string;order_number:string;status:string;created_at:string};
export function CustomerAddressBook({token,userId}:{token:string;userId:string}) {
 const [rows,setRows]=useState<Address[]>([]),[open,setOpen]=useState(false),[message,setMessage]=useState("");
 const load=()=>db("customer_addresses?select=*&order=is_default.desc,created_at.desc",token).then(setRows).catch(()=>setMessage("Address book activates after the KAOMA database upgrade is run."));
 useEffect(()=>{void load()},[token]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const makeDefault=f.get("is_default")==="on";if(makeDefault)await db(`customer_addresses?user_id=eq.${userId}`,token,{method:"PATCH",body:JSON.stringify({is_default:false})});await db("customer_addresses",token,{method:"POST",body:JSON.stringify({user_id:userId,label:String(f.get("label")),full_name:String(f.get("full_name")),phone:String(f.get("phone")),country:String(f.get("country")),address_line1:String(f.get("address_line1")),city:String(f.get("city")),region:String(f.get("region")),postal_code:String(f.get("postal_code")),is_default:makeDefault})});e.currentTarget.reset();setOpen(false);setMessage("Address saved.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Unable to save address.")}}
 async function remove(id:string){await db(`customer_addresses?id=eq.${id}`,token,{method:"DELETE"});await load()}
 return <section className="accountPanel growthCustomer"><div className="panelHead"><h3>Saved addresses</h3><button onClick={()=>setOpen(!open)}>{open?"Cancel":"+ Add address"}</button></div>{message&&<p>{message}</p>}{rows.map(a=><article className="savedAddress" key={a.id}><div><b>{a.label}{a.is_default?" · Default":""}</b><span>{a.full_name} · {a.phone}</span><span>{[a.address_line1,a.city,a.region,a.postal_code,a.country].join(", ")}</span></div><button onClick={()=>void remove(a.id)}>Remove</button></article>)}{open&&<form className="addressBookForm" onSubmit={save}><input name="label" placeholder="Label: Home, Work…" required/><input name="full_name" placeholder="Full name" required/><input name="phone" placeholder="Phone with country code" required/><input name="country" placeholder="Country" required/><input className="wide" name="address_line1" placeholder="Street address" required/><input name="city" placeholder="City" required/><input name="region" placeholder="State / Province" required/><input name="postal_code" placeholder="Postal / ZIP code" required/><label><input name="is_default" type="checkbox"/> Make default</label><button className="primary">Save address</button></form>}</section>
}
export function ReturnRequestPanel({token,orders}:{token:string;orders:Order[]}) {
 const [message,setMessage]=useState("");
 const eligible=orders.filter(o=>["delivered","shipped"].includes(o.status.toLowerCase()));
 if(!eligible.length)return null;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const orderId=String(f.get("order_id"));try{const userId=localStorage.getItem("kaoma_customer_id");await db("return_requests",token,{method:"POST",body:JSON.stringify({user_id:userId,order_id:orderId,reason:String(f.get("reason")),details:String(f.get("details")||"")})});e.currentTarget.reset();setMessage("Your request was submitted. KAOMA support will review it.")}catch(error){setMessage(error instanceof Error?error.message:"Unable to submit request.")}}
 return <section className="accountPanel growthCustomer"><h3>Request a return or refund</h3><p>Submit a request for an eligible order. Approval follows KAOMA’s return policy.</p>{message&&<p className="accountMessage">{message}</p>}<form className="returnForm" onSubmit={submit}><select name="order_id" required>{eligible.map(o=><option value={o.id} key={o.id}>Order #{o.order_number}</option>)}</select><select name="reason" required><option value="">Select reason</option><option>Damaged item</option><option>Incorrect item</option><option>Size or fit issue</option><option>Changed mind</option><option>Other</option></select><textarea name="details" placeholder="Tell us what happened" minLength={10} required/><button className="primary">Submit request</button></form></section>
}
