"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Camera, ChevronRight, CircleUserRound, FileDown, Heart, LayoutDashboard, LogOut, MapPin, PackageCheck, PackageOpen, Settings, ShoppingBag, Truck } from "lucide-react";
import { clearCustomerSession, db, getCurrentUser, getCustomerAvatarUrl, getValidCustomerSession, saveCustomerSession, sendEmailOtp, supabaseReady, uploadCustomerAvatar, verifyEmailOtp } from "@/lib/supabase-rest";
import { callingCodes, countries, splitInternationalPhone } from "@/lib/countries";
import { carrierTrackingUrl } from "@/lib/carriers";
import { CustomerAddressBook, ReturnRequestPanel } from "@/components/customer-growth-tools";

type Profile = { full_name?: string; email?: string; phone?: string; country?: string; address_line1?: string; city?: string; region?: string; postal_code?: string; avatar_path?: string };
type OrderItem = { id:string; product_name:string; quantity:number; unit_price:number; selected_size?:string; selected_colour?:string };
type Order = { id:string; order_number:string; currency:string; subtotal?:number; shipping?:number; tax?:number; total:number; status:string; payment_status:string; tracking_number?:string; created_at:string; shipping_address?:{carrier?:string;expected_dispatch_from?:string;expected_dispatch_to?:string;expected_delivery_from?:string;expected_delivery_to?:string}; order_items?:OrderItem[] };
type AccountSection = "overview" | "orders" | "tracking" | "profile";

const emptyProfile: Profile = { full_name:"", email:"", phone:"", country:"", address_line1:"", city:"", region:"", postal_code:"", avatar_path:"" };
const statusSteps = ["confirmed", "processing", "packed", "shipped", "out_for_delivery", "delivered"];
const displayDate = (value?:string) => value ? new Date(`${value}T12:00:00Z`).toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"}) : "";
const friendlyStatus = (status:string) => status.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());
const initials = (name:string, email:string) => (name.trim() || email.split("@")[0] || "K").split(/\s+/).slice(0,2).map(part => part[0]?.toUpperCase()).join("");

export function CustomerAccount() {
  const [email,setEmail]=useState(""), [message,setMessage]=useState(""), [token,setToken]=useState(""), [userId,setUserId]=useState("");
  const [codeSent,setCodeSent]=useState(false), [busy,setBusy]=useState(false), [loading,setLoading]=useState(true);
  const [profile,setProfile]=useState<Profile>(emptyProfile), [orders,setOrders]=useState<Order[]>([]);
  const [section,setSection]=useState<AccountSection>("overview"), [avatarUrl,setAvatarUrl]=useState(""), [wishlistCount,setWishlistCount]=useState(0);
  const [dialCode,setDialCode]=useState("+91"), [phoneNumber,setPhoneNumber]=useState("");

  const loadAccount=useCallback(async(accessToken:string,id:string,accountEmail="")=>{
    try {
      const [profileRows,orderRows]=await Promise.all([
        db(`profiles?user_id=eq.${id}&select=*`,accessToken),
        db(`orders?user_id=eq.${id}&select=id,order_number,currency,subtotal,shipping,tax,total,status,payment_status,tracking_number,shipping_address,created_at,order_items(id,product_name,quantity,unit_price,selected_size,selected_colour)&order=created_at.desc`,accessToken),
      ]);
      const nextProfile={...emptyProfile,email:accountEmail,...(profileRows[0]||{})};
      const parsedPhone=splitInternationalPhone(nextProfile.phone||"");
      setProfile(nextProfile); setDialCode(parsedPhone.dial); setPhoneNumber(parsedPhone.number); setOrders(orderRows||[]);
      if(nextProfile.avatar_path) void getCustomerAvatarUrl(nextProfile.avatar_path,accessToken).then(setAvatarUrl).catch(()=>{});
    } catch(error) { setMessage(error instanceof Error?error.message:"Unable to load your account."); }
    finally { setLoading(false); }
  },[]);

  useEffect(()=>{
    setWishlistCount(JSON.parse(localStorage.getItem("kaoma_wishlist")||"[]").length);
    const hash=new URLSearchParams(location.hash.replace(/^#/,"")), accessToken=hash.get("access_token")||localStorage.getItem("kaoma_customer_token")||"", storedId=localStorage.getItem("kaoma_customer_id")||"", storedEmail=localStorage.getItem("kaoma_customer_email")||"";
    if(!accessToken){setLoading(false);return;}
    if(storedId){setToken(accessToken);setUserId(storedId);setEmail(storedEmail);setProfile(current=>({...current,email:storedEmail}));setLoading(false);}
    void (async()=>{try{
      const validToken=hash.get("access_token")?accessToken:await getValidCustomerSession();
      const user=await getCurrentUser(validToken), accountEmail=user.email||storedEmail;
      localStorage.setItem("kaoma_customer_token",validToken); localStorage.setItem("kaoma_customer_id",user.id); localStorage.setItem("kaoma_customer_email",accountEmail);
      setToken(validToken);setUserId(user.id);setEmail(accountEmail);
      if(hash.get("access_token")) history.replaceState(null,"","/account");
      await loadAccount(validToken,user.id,accountEmail);
    }catch{clearCustomerSession();setToken("");setUserId("");setMessage("Your session expired. Please request a new OTP.");setLoading(false);}})();
  },[loadAccount]);

  const activeOrders=useMemo(()=>orders.filter(order=>!["delivered","cancelled"].includes(order.status.toLowerCase())),[orders]);
  const updateField=(field:keyof Profile,value:string)=>setProfile(current=>({...current,[field]:value}));

  async function requestCode(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");try{await sendEmailOtp(email);setCodeSent(true);setMessage("Enter the OTP sent to your email.");}catch(error){setMessage(error instanceof Error?error.message:"Unable to send code.");}finally{setBusy(false);}}
  async function confirmCode(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");try{const form=new FormData(event.currentTarget),code=String(form.get("code")).trim();if(!/^\d{8}$/.test(code))throw new Error("Enter the complete 8-digit OTP from your email.");const session=await verifyEmailOtp(email,code);saveCustomerSession(session,email);setToken(session.access_token);setUserId(session.user.id);setLoading(false);setMessage("Welcome to your KAOMA account.");void loadAccount(session.access_token,session.user.id,session.user.email||email);}catch(error){setMessage(error instanceof Error?error.message:"Unable to verify code.");}finally{setBusy(false);}}
  async function saveProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");try{const cleanNumber=phoneNumber.replace(/[^0-9]/g,"");const body={...profile,phone:cleanNumber?`${dialCode}${cleanNumber}`:"",user_id:userId,email:localStorage.getItem("kaoma_customer_email")||profile.email||email};await db("profiles?on_conflict=user_id",token,{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(body)});setProfile(current=>({...current,phone:body.phone}));setMessage("Your profile and international delivery address have been saved.");}catch(error){setMessage(error instanceof Error?error.message:"Unable to save details.");}finally{setBusy(false);}}
  async function changeAvatar(file?:File){if(!file)return;setBusy(true);setMessage("");try{const path=await uploadCustomerAvatar(file,token,userId);await db("profiles?on_conflict=user_id",token,{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({user_id:userId,email:profile.email||email,avatar_path:path})});setProfile(current=>({...current,avatar_path:path}));setAvatarUrl(await getCustomerAvatarUrl(path,token));setMessage("Your profile photo has been updated.");}catch(error){setMessage(error instanceof Error?error.message:"Unable to upload photo.");}finally{setBusy(false);}}
  function logout(){clearCustomerSession();location.reload();}

  if(loading)return null;
  if(!token)return <div className="accountBox accountLogin"><span className="accountEyebrow">PRIVATE · PASSWORDLESS · SECURE</span><h2>Sign in to KAOMA</h2><p>Enter your email and we’ll send a one-time login code.</p>{!codeSent?<form onSubmit={requestCode}><label>Email address<input value={email} onChange={event=>setEmail(event.target.value)} type="email" autoComplete="email" placeholder="you@example.com" required/></label>{message&&<div className="accountMessage">{message}</div>}{!supabaseReady&&<div className="adminNotice">Customer sign-in is temporarily unavailable. Please try again shortly.</div>}<button className="primary" disabled={busy||!supabaseReady}>{busy?"Sending OTP…":"Send OTP"}</button></form>:<form onSubmit={confirmCode}><label>Enter the 8-digit OTP sent to {email}<input name="code" inputMode="numeric" autoComplete="one-time-code" minLength={8} maxLength={8} pattern="[0-9]{8}" placeholder="8-digit OTP" required/></label>{message&&<div className="accountMessage">{message}</div>}<button className="primary" disabled={busy}>{busy?"Checking…":"Verify and sign in"}</button><button className="textButton" type="button" onClick={()=>setCodeSent(false)}>Use another email</button></form>}<small>New customers are registered automatically. No password is required.</small></div>;

  const navItems:{id:AccountSection;label:string;icon:typeof LayoutDashboard}[]=[{id:"overview",label:"Overview",icon:LayoutDashboard},{id:"orders",label:"My orders",icon:ShoppingBag},{id:"tracking",label:"Track order",icon:Truck},{id:"profile",label:"Profile & address",icon:Settings}];
  const avatar=<>{avatarUrl?<img src={avatarUrl} alt="Customer profile"/>:<span>{initials(profile.full_name||"",profile.email||email)}</span>}</>;

  return <div className="customerDashboard">
    <aside className="customerAccountSide"><div className="customerIdentity"><div className="customerAvatar">{avatar}<label title="Change profile photo"><Camera/><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>void changeAvatar(event.target.files?.[0])}/></label></div><div><small>WELCOME</small><strong>{profile.full_name||"KAOMA customer"}</strong><span>{profile.email||email}</span></div></div><nav aria-label="Customer account">{navItems.map(({id,label,icon:Icon})=><button key={id} className={section===id?"active":""} onClick={()=>setSection(id)}><Icon/><span>{label}</span><ChevronRight/></button>)}<a href="/wishlist"><Heart/><span>Wishlist</span><b>{wishlistCount}</b></a><button onClick={logout}><LogOut/><span>Sign out</span></button></nav></aside>
    <main className="customerAccountMain"><header className="accountMobileHead"><div className="customerAvatar small">{avatar}</div><div><small>MY KAOMA</small><strong>{profile.full_name||"Your account"}</strong></div></header><div className="accountMobileNav">{navItems.map(({id,label,icon:Icon})=><button key={id} className={section===id?"active":""} onClick={()=>setSection(id)}><Icon/>{label}</button>)}</div>{message&&<div className="accountMessage">{message}</div>}
      {section==="overview"&&<section className="accountSection"><AccountTitle eyebrow="YOUR PRIVATE SPACE" title="Account overview" text="Manage orders, delivery details and favourites in one place."/><div className="accountStatGrid"><article><PackageOpen/><div><strong>{orders.length}</strong><span>Total orders</span></div></article><article><Truck/><div><strong>{activeOrders.length}</strong><span>Active deliveries</span></div></article><article><Heart/><div><strong>{wishlistCount}</strong><span>Saved favourites</span></div></article></div><div className="accountOverviewGrid"><article className="accountPanel"><div className="panelHead"><h3>Recent orders</h3><button onClick={()=>setSection("orders")}>View all</button></div>{orders.length?orders.slice(0,3).map(order=><OrderRow key={order.id} order={order} onTrack={()=>setSection("tracking")}/>):<EmptyOrders/>}</article><article className="accountPanel"><div className="panelHead"><h3>Delivery details</h3><button onClick={()=>setSection("profile")}>Edit</button></div><AddressSummary profile={profile}/></article></div></section>}
      {section==="orders"&&<section className="accountSection"><AccountTitle eyebrow="ORDER HISTORY" title="My orders" text="Review every KAOMA purchase and its current status."/><div className="accountPanel orderHistory">{orders.length?orders.map(order=><OrderCard key={order.id} order={order} profile={profile} onTrack={()=>setSection("tracking")}/>):<EmptyOrders/>}</div><ReturnRequestPanel token={token} orders={orders}/></section>}
      {section==="tracking"&&<section className="accountSection"><AccountTitle eyebrow="DELIVERY UPDATES" title="Track your orders" text="Tracking appears here as soon as your order is dispatched."/><div className="trackingList">{activeOrders.length?activeOrders.map(order=><TrackingCard key={order.id} order={order}/>):<div className="accountPanel accountEmpty"><PackageCheck/><h3>No active deliveries</h3><p>Your active order tracking will appear here.</p></div>}</div></section>}
      {section==="profile"&&<section className="accountSection"><AccountTitle eyebrow="PROFILE & DELIVERY" title="Your details" text="Keep your information accurate for smooth international delivery."/><form className="profileForm" onSubmit={saveProfile}><div className="profileFormHead"><CircleUserRound/><div><h3>Personal information</h3><p>Your email is secured by passwordless verification.</p></div></div><div className="profileFields"><label>Full name<input value={profile.full_name||""} onChange={event=>updateField("full_name",event.target.value)} autoComplete="name" required/></label><label>Email address<input value={profile.email||email} readOnly/></label><label>Phone number<div className="phoneField"><select aria-label="Country calling code" value={dialCode} onChange={event=>setDialCode(event.target.value)}>{callingCodes.map(code=><option key={code} value={code}>{code}</option>)}</select><input value={phoneNumber} onChange={event=>setPhoneNumber(event.target.value)} placeholder="Mobile number" inputMode="tel" autoComplete="tel-national" required/></div></label><label>Country / region<select value={profile.country||""} onChange={event=>{const country=event.target.value;updateField("country",country);const match=countries.find(item=>item.name===country);if(match&&match.dial!=="+")setDialCode(match.dial);}} autoComplete="country-name" required><option value="" disabled>Select country / region</option>{countries.map(country=><option key={country.code} value={country.name}>{country.name}</option>)}</select></label><label className="wide">Street address<input value={profile.address_line1||""} onChange={event=>updateField("address_line1",event.target.value)} autoComplete="street-address" placeholder="House/building, street and area" required/></label><label>City<input value={profile.city||""} onChange={event=>updateField("city",event.target.value)} autoComplete="address-level2" required/></label><label>State / province<input value={profile.region||""} onChange={event=>updateField("region",event.target.value)} autoComplete="address-level1" required/></label><label>Postal / ZIP code<input value={profile.postal_code||""} onChange={event=>updateField("postal_code",event.target.value)} autoComplete="postal-code" required/></label></div><button className="primary" disabled={busy}>{busy?"Saving…":"Save profile and address"}</button></form><CustomerAddressBook token={token} userId={userId}/></section>}
    </main>
  </div>;
}

function AccountTitle({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="accountTitle"><span>{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>}
function AddressSummary({profile}:{profile:Profile}){if(!profile.address_line1)return <div className="emptyAddress"><MapPin/><p>No delivery address saved yet.</p></div>;return <address><strong>{profile.full_name}</strong><span>{profile.address_line1}</span><span>{[profile.city,profile.region,profile.postal_code].filter(Boolean).join(", ")}</span><span>{profile.country}</span>{profile.phone&&<span>{profile.phone}</span>}</address>}
function EmptyOrders(){return <div className="emptyOrders"><PackageOpen/><h3>No orders yet</h3><p>Your purchases will appear here after checkout.</p><a className="primary" href="/#collection">Explore collection</a></div>}
function OrderRow({order,onTrack}:{order:Order;onTrack:()=>void}){return <div className="orderRow"><div><strong>#{order.order_number}</strong><span>{new Date(order.created_at).toLocaleDateString()}</span></div><div><b>{order.currency} {Number(order.total).toFixed(2)}</b><span className={`statusPill ${order.status.toLowerCase()}`}>{friendlyStatus(order.status)}</span></div><button onClick={onTrack}>Track</button></div>}
function OrderCard({order,onTrack,profile}:{order:Order;onTrack:()=>void;profile:Profile}){return <article className="orderCard"><div className="orderCardHead"><div><small>ORDER</small><strong>#{order.order_number}</strong><span>{new Date(order.created_at).toLocaleDateString()}</span></div><span className={`statusPill ${order.status.toLowerCase()}`}>{friendlyStatus(order.status)}</span></div><div className="orderItems">{order.order_items?.length?order.order_items.map(item=><div key={item.id}><span>{item.quantity} × {item.product_name}</span><small>{[item.selected_colour,item.selected_size].filter(Boolean).join(" · ")}</small></div>):<span>Order details</span>}</div><footer><div><small>TOTAL</small><strong>{order.currency} {Number(order.total).toFixed(2)}</strong></div><div><small>PAYMENT</small><strong>{friendlyStatus(order.payment_status)}</strong></div><button onClick={()=>openInvoice(order,profile)}><FileDown/> Invoice</button><button onClick={onTrack}><Truck/> Track order</button></footer></article>}
function TrackingCard({order}:{order:Order}){const current=statusSteps.indexOf(order.status.toLowerCase());const shipping=order.shipping_address||{};return <article className="accountPanel trackingCard"><div className="trackingHead"><div><small>ORDER</small><strong>#{order.order_number}</strong></div><span className={`statusPill ${order.status.toLowerCase()}`}>{friendlyStatus(order.status)}</span></div><div className="trackingSteps">{statusSteps.map((step,index)=><div key={step} className={current>=0&&index<=current?"complete":""}><i>{index<current?"✓":index+1}</i><span>{friendlyStatus(step)}</span></div>)}</div><div className="deliveryEstimate">{shipping.expected_dispatch_from&&<p><strong>Preparing:</strong> {displayDate(shipping.expected_dispatch_from)}{shipping.expected_dispatch_to&&shipping.expected_dispatch_to!==shipping.expected_dispatch_from?` – ${displayDate(shipping.expected_dispatch_to)}`:""}</p>}{shipping.expected_delivery_from&&<p><strong>Expected delivery:</strong> {displayDate(shipping.expected_delivery_from)}{shipping.expected_delivery_to&&shipping.expected_delivery_to!==shipping.expected_delivery_from?` – ${displayDate(shipping.expected_delivery_to)}`:""}</p>}<p><strong>Carrier:</strong> {shipping.carrier||"India Post"}</p></div>{order.tracking_number?<p><strong>Tracking number:</strong> {order.tracking_number} · <a href={carrierTrackingUrl(shipping.carrier,order.tracking_number)} target="_blank" rel="noreferrer">Track with {shipping.carrier||"carrier"}</a></p>:<p>Tracking number will be added after dispatch.</p>}</article>}


function invoiceEscape(value: unknown) {
  return String(value ?? "").replace(/[&<>"']/g, character => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[character] || character));
}
function openInvoice(order: Order, profile: Profile) {
  const money = (value: number) => `${invoiceEscape(order.currency || "INR")} ${Number(value || 0).toFixed(2)}`;
  const rows = (order.order_items || []).map(item => `<tr><td>${invoiceEscape(item.product_name)}<small>${invoiceEscape([item.selected_colour,item.selected_size].filter(Boolean).join(" · "))}</small></td><td>${item.quantity}</td><td>${money(item.unit_price)}</td><td>${money(item.quantity * item.unit_price)}</td></tr>`).join("");
  const address = [profile.address_line1,profile.city,profile.region,profile.postal_code,profile.country].filter(Boolean).map(invoiceEscape).join(", ");
  const fallback = `<tr><td>KAOMA order</td><td>1</td><td></td><td>${money(order.total)}</td></tr>`;
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>KAOMA Invoice ${invoiceEscape(order.order_number)}</title><style>body{font-family:Arial,sans-serif;color:#39243f;margin:0;padding:40px}header{display:flex;justify-content:space-between;border-bottom:3px solid #b92c61;padding-bottom:20px}h1{font-family:Georgia,serif;margin:0;color:#54233a}.brand{font-size:30px;letter-spacing:.15em;color:#b92c61}.meta,.customer{margin:24px 0;line-height:1.6}table{width:100%;border-collapse:collapse}th,td{padding:12px 8px;border-bottom:1px solid #eadcc8;text-align:right}th:first-child,td:first-child{text-align:left}td small{display:block;color:#806d76;margin-top:4px}.totals{margin:22px 0 0 auto;width:300px}.totals p{display:flex;justify-content:space-between}.total{font-size:20px;border-top:2px solid #54233a;padding-top:12px}footer{margin-top:55px;border-top:1px solid #eadcc8;padding-top:16px;color:#806d76;font-size:12px}@media print{body{padding:15px}}</style></head><body><header><div><div class="brand">KAOMA</div><p>Private, discreet commerce</p><p><b>Seller:</b> KAOMA, India<br><b>Customer support:</b> <a href="mailto:kaomaglobal@gmail.com">kaomaglobal@gmail.com</a><br><b>Website:</b> <a href="https://kaoma.in">kaoma.in</a></p></div><div><h1>Order Invoice</h1><p>#${invoiceEscape(order.order_number)}</p></div></header><section class="meta"><b>Invoice date:</b> ${new Date(order.created_at).toLocaleDateString()}<br><b>Payment:</b> ${invoiceEscape(friendlyStatus(order.payment_status))}</section><section class="customer"><b>Bill / deliver to</b><br>${invoiceEscape(profile.full_name || "KAOMA customer")}<br>${invoiceEscape(profile.email || "")}<br>${address}</section><table><thead><tr><th>Product</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>${rows || fallback}</tbody></table><div class="totals">${order.subtotal!=null?`<p><span>Subtotal</span><b>${money(order.subtotal)}</b></p>`:""}${order.shipping!=null?`<p><span>Shipping</span><b>${money(order.shipping)}</b></p>`:""}${order.tax?`<p><span>Tax</span><b>${money(order.tax)}</b></p>`:""}<p class="total"><span>Total paid</span><b>${money(order.total)}</b></p></div><footer>Thank you for choosing KAOMA.<br>Customer support: kaomaglobal@gmail.com · Website: kaoma.in<br>This is an order invoice/payment receipt. Save it as PDF using your browser's print window.</footer><script>window.onload=()=>setTimeout(()=>window.print(),250)</script></body></html>`;
  const url = URL.createObjectURL(new Blob([html], { type: "text/html" }));
  window.open(url, "_blank", "noopener,noreferrer");
  setTimeout(() => URL.revokeObjectURL(url), 60000);
}
